name: Ingest daily

on:
  schedule:
    - cron: "10 2 * * *"   # runs daily at 02:10 UTC
  workflow_dispatch:        # lets you run it manually

permissions:
  contents: write           # needed to push DB changes

jobs:
  run-ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ingest
        run: python ingest.py

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Ingest: daily update [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
